.PHONY: clean, get, generate, regenerate, generate-watch, build_apk, format, icon, splash, lint, fix, sort

clean: ## Cleans the environment
	@echo "╠ Cleaning the project..."
	@fvm flutter clean

get: ## Get project dependencies
	@echo "╠ Get dependencies"
	@fvm flutter pub get

generate: ## Generates autogenerated code
	@echo "╠ Generating code"
	@fvm flutter pub run build_runner build

regenerate: ## Regenerates autogenerated code
	@echo "╠ Re-generating code"
	@fvm flutter pub run build_runner build --delete-conflicting-outputs

generate-watch: ## Generates autogenerated code
	@echo "╠ Generating code"
	@fvm flutter pub run build_runner watch

build_apk: ## Build mobile application
	@echo "╠ Building mobile application for flavour $(flavour)"
	@fvm flutter build apk --release --flavor $(flavour) -t lib/main_$(flavour).dart --obfuscate --split-debug-info=./obfuscatation/debug

format: ## Formats the code
	@echo "╠ Formatting the code"
	dart format .

icon: ## Generates launcher icon
	@echo "╠ Making launcher icon"
	@fvm flutter pub run flutter_launcher_icons

splash: ## Generates native splash
	@echo "╠ Making native splash"
	@fvm flutter pub run flutter_native_splash:create

lint: ## Lints the code
	@echo "╠ Verifying code..."
	@fvm flutter analyze . || (echo "Error in project"; exit 1)

fix: ## Fixing the code
	@echo "╠ Fixing code..."
	dart fix --apply

sort: ## Sort dependencies
	@echo "╠ Sorting dependencies..."
	@fvm flutter pub run import_sorter:main -e
